apiVersion: v2
name: financials
description: Helm chart for financials
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
- name: postgresql
  version: 10.12.4
  repository: https://charts.bitnami.com/bitnami
