apiVersion: v2
name: financials
description: Helm chart for financials
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: 10.12.4
  repository: https://charts.bitnami.com/bitnami
