financials:
  # -- cron schedule
  cronSchedule: "0 */4 * * *"
  alphavantageApiKey: secret
  image:
    # -- Respository of the image.
    repository: ghcr.io/ashwinath/financials
    # -- Image pull policy in Kubernetes
    pullPolicy: Always
    # -- Override this value for the desired image tag
    tag: latest
  # -- telegram bot dump endpoint, include scheme as well.
  telegramBotUrl: http://<url here>

  # -- Resources requests and limits for the financial app
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- CSV values for the trades
  trades: |-
    date_purchased,symbol,trade_type,price_each,quantity
    2021-03-11,IWDA.LON,buy,76.34,10

  # -- CSV values for the expenses
  expenses: |-
    date,type,amount
    2020-03-31,Credit Card,500
    2020-03-31,Reimbursement,-200
    2020-03-31,Tithe,800

  # -- CSV values for the assets
  assets: |-
    date,type,amount
    2020-03-31,CPF,1000
    2020-03-31,Bank,20000
    2020-03-31,Mortgage,-40000
    2020-03-31,Investments,20000

  # -- CSV values for the income
  income: |-
    date,type,amount
    2021-03-11,Base,500
    2021-03-11,Bonus,200

  # -- YAML values for mortgage
  mortgage: |-
    mortgages:
    - total: 50000.0
      mortgage_first_payment: 2022-10-10
      mortgage_duration_in_years: 25
      mortgage_end_date: 2047-10-10
      interest_rate_percentage: 2.6
      downpayments:
      - date: 2021-10-10
        sum: 1000.0
      - date: 2021-12-12
        sum: 20000.0

  # -- CSV values for shared expenses
  shared_expenses: |-
    date,type,amount
    2023-01-01,Special:Renovations,5000.00
    2023-01-01,Electricity,100.00
    2023-01-01,Water,50.00
    2023-01-01,Gas,30.00
    2023-01-01,Grocery,300.00
    2023-01-01,Eating Out,500.00


postgresql:
  # -- Resources requests and limits for the database
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  primary:
    persistence:
      # -- Persist Postgresql data in a Persistent Volume Claim 
      enabled: true
  auth:
    # -- Password for postgresql database, highly recommended to change this value
    postgresqlPassword: password
