{
 "title": "Financials",
 "tags": [ "financials" ],
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Financials Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Net Assets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    transaction_date as \"time\",\n    SUM(amount) as \"Amount\"\n  FROM assets\n  WHERE\n    $__timeFilter(transaction_date)\n  group by transaction_date\n  order by transaction_date"
    }
   ]
  },
  {
   "title": "Net Liquid Assets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    transaction_date as \"time\",\n    type,\n    amount AS \"Amount\"\n  FROM assets\n  WHERE\n    $__timeFilter(transaction_date)\n    AND type IN ('Bank', 'MMF', 'Investments', 'Bonds')\n  group by transaction_date, type, amount\n  order by transaction_date"
    }
   ]
  },
  {
   "title": "Net Illiquid Assets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    transaction_date as \"time\",\n    type,\n    amount AS \"Amount\"\n  FROM assets\n  WHERE\n    $__timeFilter(transaction_date)\n    AND type IN ('OA', 'SA', 'Medisave', 'SRS', 'House')\n  group by transaction_date, type, amount\n  order by transaction_date"
    }
   ]
  },
  {
   "title": "Inflow/Outflow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Salary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    transaction_date as \"time\",\n    type,\n    amount AS \"Amount\"\n  FROM incomes\n  WHERE\n    $__timeFilter(transaction_date)\n  group by transaction_date, type, amount\n  order by transaction_date"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH cc as (\n    SELECT\n      transaction_date as \"transaction_date\",\n      sum(amount) as \"amount\"\n    FROM\n      expenses\n    WHERE\n      $__timeFilter(transaction_date)\n      AND type in ('Credit Card', 'Reimbursement')\n    group by transaction_date\n    order by transaction_date\n  )\n  SELECT\n      transaction_date as \"time\",\n      type,\n      amount AS \"Amount\"\n  FROM expenses\n  WHERE\n      $__timeFilter(transaction_date)\n      AND type not in ('Credit Card', 'Reimbursement')\n      AND type not like 'Special:%'\n  UNION select transaction_date as \"time\", 'Credit Card' as type, amount from cc\n  group by transaction_date, type, amount\n  order by time"
    }
   ]
  },
  {
   "title": "Savings Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH expenditure AS (\n  select date_trunc('month', transaction_date) as time, sum(amount) as Amount from expenses where $__timeFilter(transaction_date) and type not like 'Special:%' group by time\n),\nincome as (\n  select date_trunc('month', transaction_date) as time, sum(amount) as Amount from incomes where $__timeFilter(transaction_date) and type in ('Base', 'Base Bonus') group by time\n)\nSELECT\n  expenditure.time + interval '1 month' - interval '1 day' AS \"time\",\n  CASE \n    WHEN income.amount != 0 then (1 - (expenditure.amount / income.amount)) \n    ELSE 0\n  END as \"Savings Rate\"\nFROM expenditure inner join income on income.time = expenditure.time\nWHERE $__timeFilter(expenditure.time)\nORDER BY expenditure.time;"
    }
   ]
  },
  {
   "title": "Special Expenses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n      transaction_date as \"time\",\n      type,\n      amount AS \"Amount\"\n  FROM expenses\n  WHERE\n      $__timeFilter(transaction_date)\n      AND type like 'Special:%'\n  group by transaction_date, type, amount\n  order by time"
    }
   ]
  },
  {
   "title": "Shared Expenses (2 people)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n      expense_date as \"time\",\n      sum(amount) AS \"Amount\"\n  FROM shared_expense\n  WHERE\n      $__timeFilter(expense_date)\n      AND type not like 'Special:%'\n  group by expense_date\n  order by time"
    }
   ]
  },
  {
   "title": "Special Shared Expenses (2 people)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n      expense_date as \"time\",\n      sum(amount) AS \"Amount\"\n  FROM shared_expense\n  WHERE\n      $__timeFilter(expense_date)\n      AND type like 'Special:%'\n  group by expense_date\n  order by time"
    }
   ]
  },
  {
   "title": "Mortgage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mortgage Payment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date as \"time\",\n    interest_paid as \"Interest Paid\",\n    principal_paid AS \"Principal Paid\"\nFROM mortgage\nWHERE\n    $__timeFilter(date)\ngroup by date, interest_paid, principal_paid\norder by time"
    }
   ]
  },
  {
   "title": "Mortgage Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date as \"time\",\n    total_interest_left as \"Interest Left\",\n    total_principal_left AS \"Principal Left\"\nFROM mortgage\nWHERE\n    $__timeFilter(date)\ngroup by date, total_interest_left, total_principal_left\norder by time"
    }
   ]
  },
  {
   "title": "Mortgage Serviced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date as \"time\",\n    total_interest_paid as \"Total Interest Paid\",\n    total_principal_paid AS \"Total Principal Paid\"\nFROM mortgage\nWHERE\n    $__timeFilter(date)\ngroup by date, total_interest_paid, total_principal_paid\norder by time"
    }
   ]
  },
  {
   "title": "Financial Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Emergency Funds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Months" } },
   "targets": [
    {
     "rawSql": "WITH avg_exp AS (\n    select expense_date + INTERVAL '1 day' as \"expense_date\", amount from average_expenditures\n),\nbank AS (\n    select transaction_date, sum(amount) as amount from assets where type in ('Bank', 'Bonds') group by transaction_date\n)\nselect\n    a.expense_date as \"time\",\n    b.amount / a.amount as \"months\"\nfrom\n    avg_exp a inner join bank b on a.expense_date = b.transaction_date\nWHERE $__timeFilter(a.expense_date)\nORDER BY a.expense_date;"
    }
   ]
  },
  {
   "title": "Runway Based on 70% Equity + Bank + Bonds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Months" } },
   "targets": [
    {
     "rawSql": "WITH avg_exp AS (\n    select expense_date + INTERVAL '1 day' as \"expense_date\", amount from average_expenditures\n),\nbank AS (\n    select transaction_date, sum(amount) as amount from assets where type in ('Bank', 'Bonds') group by transaction_date\n),\nequity AS (\n    select transaction_date, amount from assets where type = 'Investments'\n)\nselect\n    a.expense_date as \"time\",\n    (b.amount + (c.amount * 0.7)) / a.amount as \"months\"\nfrom\n    avg_exp a inner join bank b on a.expense_date = b.transaction_date\n    inner join equity c on a.expense_date = c.transaction_date\nWHERE $__timeFilter(a.expense_date)\nORDER BY a.expense_date;"
    }
   ]
  },
  {
   "title": "Financial Independence Quotient (3% Withdrawal)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH avg_exp AS (\n    select expense_date + INTERVAL '1 day' as \"expense_date\", amount from average_expenditures\n),\nequity AS (\n    select transaction_date, sum(amount) as amount from assets where type in ('Investments', 'Bonds') group by transaction_date\n)\nselect\n    a.expense_date as \"time\",\n    (0.03 * c.amount) / (a.amount * 12) as \"quotient\"\nfrom\n    avg_exp a inner join equity c on a.expense_date = c.transaction_date\nWHERE $__timeFilter(a.expense_date)\nORDER BY a.expense_date;"
    }
   ]
  },
  {
   "title": "Current Investments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Portfolio",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "\n    WITH total AS (\n      SELECT\n        sum(nav) AS total\n      FROM portfolios\n      WHERE\n        trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n    ),\n    stock as (\n      SELECT\n        symbol,\n        price\n      FROM stocks\n      WHERE\n        trade_date = (\n          SELECT\n            trade_date\n          FROM stocks\n          ORDER BY trade_date desc\n          LIMIT 1\n        )\n    )\n    SELECT\n      trade_date as time,\n      stock.symbol as symbol,\n      stock.price as current_price,\n      quantity as quantity,\n      sum(nav) as nav,\n      sum(principal) as principal,\n      (sum(nav) - sum(principal)) / sum(principal) as returns,\n      sum(nav)/total.total as percentage\n    FROM portfolios inner join stock on portfolios.symbol = stock.symbol, total\n    WHERE\n      trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n    group by trade_date, stock.symbol, total.total, quantity, stock.price\n    order by trade_date"
    }
   ]
  },
  {
   "title": "Principal",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    sum(principal) as \"principal\"\n  FROM portfolios\n  WHERE\n    trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "NAV",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    sum(nav) as \"nav\"\n  FROM portfolios\n  WHERE\n    trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "Simple Returns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    (sum(nav) - sum(principal)) / sum(principal) as \"returns\"\n  FROM portfolios\n  WHERE\n    trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "Portfolio",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n      trade_date as \"time\",\n      symbol,\n      sum(nav) as \"nav\"\n    FROM portfolios\n    WHERE\n      trade_date=DATE_TRUNC('day', CURRENT_TIMESTAMP - INTERVAL '1 day') + INTERVAL '8 hours'\n    group by trade_date, symbol\n    order by trade_date"
    }
   ]
  },
  {
   "title": "Trades",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "select TO_CHAR(date_purchased, 'YYYY/MM/DD') as Date, trade_type as Type, symbol as Symbol, price_each As Price, quantity as Quantity, price_each * quantity as Cost from trades order by date_purchased desc;"
    }
   ]
  },
  {
   "title": "Investment Historical Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Portfolio Simple Returns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    (sum(nav) - sum(principal)) / sum(principal) as \"returns\"\n  FROM portfolios\n  WHERE\n    $__timeFilter(trade_date)\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "Portfolio NAV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    sum(nav) as \"nav\",\n    sum(principal) as \"principal\"\n  FROM portfolios\n  WHERE\n    $__timeFilter(trade_date)\n  group by trade_date\n  order by trade_date"
    }
   ]
  },
  {
   "title": "Simple Returns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    symbol,\n    (sum(nav) - sum(principal))/ sum(principal) as \"returns\"\n  FROM portfolios\n  WHERE\n    $__timeFilter(trade_date)\n  group by trade_date, symbol\n  order by trade_date"
    }
   ]
  },
  {
   "title": "NAV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n    trade_date as \"time\",\n    symbol,\n    sum(nav) as \"nav\"\n  FROM portfolios\n  WHERE\n    $__timeFilter(trade_date)\n  group by trade_date, symbol\n  order by trade_date"
    }
   ]
  }
 ]
}