Database:
  Host: localhost
  Port: 5432
  User: postgres
  Password: password
  Name: postgres
  TimeZone: Asia/Singapore
  BatchInsertSize: 100

AlphaVantageAPIKey: test
TradesCSVFile: ./trades.csv
ExpensesCSVFile: ./expenses.csv
AssetsCSVFile: ./assets.csv
