apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "financials.fullname" . }}
  labels:
    {{- include "financials.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.financials.cronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: grafana-init
            image: "{{ .Values.financials.financialsGrafana.image.repository }}:{{ .Values.financials.financialsGrafana.image.tag }}"
            command: ["/bin/sh", "-c"]
            args:
            - /app/load.sh
            env:
            - name: GRAFANA_API_KEY
              value: {{ .Values.financials.financialsGrafana.apiKey }}
            - name: GRAFANA_ENDPOINT
              value: {{ .Values.financials.financialsGrafana.endpoint }}
          containers:
          - name: financials
            image: "{{ .Values.financials.image.repository }}:{{ .Values.financials.image.tag }}"
            imagePullPolicy: {{ .Values.financials.image.pullPolicy }}
            env:
            - name: CONFIG_FILE
              value: /etc/financials/config.yaml
            resources:
              {{- toYaml .Values.financials.resources | nindent 16 }}
            volumeMounts:
            - name: config
              mountPath: /etc/financials
            - name: trades-csv
              mountPath: {{ .Values.financials.tradeCSVDirectory }}
            - name: expenses-csv
              mountPath: {{ .Values.financials.expensesCSVDirectory }}
            - name: assets-csv
              mountPath: {{ .Values.financials.assetsCSVDirectory }}
          restartPolicy: OnFailure
          volumes:
          - name: config
            secret:
              secretName: {{ template "financials.fullname" .}}-config
          - name: trades-csv
            configMap:
              name: {{ .Release.Name }}-trades-csv
          - name: expenses-csv
            configMap:
              name: {{ .Release.Name }}-expenses-csv
          - name: assets-csv
            configMap:
              name: {{ .Release.Name }}-assets-csv
