apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "financials.fullname" . }}
  labels:
    {{- include "financials.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.financials.cronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: grafana-init
            image: "{{ .Values.financials.financialsGrafana.image.repository }}:{{ .Values.financials.financialsGrafana.image.tag }}"
            command: ["/bin/sh", "-c"]
            args:
            - /app/load.sh
            env:
            - name: GRAFANA_API_KEY
              value: {{ .Values.financials.financialsGrafana.apiKey }}
            - name: GRAFANA_ENDPOINT
              value: {{ .Values.financials.financialsGrafana.endpoint }}
          containers:
          - name: financials
            image: "{{ .Values.financials.image.repository }}:{{ .Values.financials.image.tag }}"
            imagePullPolicy: {{ .Values.financials.image.pullPolicy }}
            env:
            - name: CONFIG_FILE
              value: /etc/financials/config.yaml
            resources:
              {{- toYaml .Values.financials.resources | nindent 16 }}
            args:
            - ./financials
            - --database-url
            - postgres://postgres:{{ .Values.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local/postgres
            - --alphavantage-key
            - {{ .Values.financials.alphavantageApiKey }}
            - --trades-csv
            - /etc/trades/trades.csv
            - --assets-csv
            - /etc/assets/assets.csv
            - --income-csv
            - /etc/income/income.csv
            - --expenses-csv
            - /etc/expenses/expenses.csv
            - --mortgage-yaml
            - /etc/mortgage/mortgage.yaml
            - --shared-expense-csv
            - /etc/shared-expenses/shared_expenses.csv
            - --telegram-bot-endpoint
            - "{{ .Values.financials.telegramBotUrl }}"
            volumeMounts:
            - name: trades-csv
              mountPath: /etc/trades
            - name: expenses-csv
              mountPath: /etc/expenses
            - name: assets-csv
              mountPath: /etc/assets
            - name: income-csv
              mountPath: /etc/income
            - name: mortgage-yaml
              mountPath: /etc/mortgage
            - name: shared-expenses-csv
              mountPath: /etc/shared-expenses
          restartPolicy: OnFailure
          volumes:
          - name: trades-csv
            configMap:
              name: {{ .Release.Name }}-trades-csv
          - name: expenses-csv
            configMap:
              name: {{ .Release.Name }}-expenses-csv
          - name: assets-csv
            configMap:
              name: {{ .Release.Name }}-assets-csv
          - name: income-csv
            configMap:
              name: {{ .Release.Name }}-income-csv
          - name: mortgage-yaml
            configMap:
              name: {{ .Release.Name }}-mortgage-yaml
          - name: shared-expenses-csv
            configMap:
              name: {{ .Release.Name }}-shared-expenses-csv
