apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "financials.fullname" . }}
  labels:
    {{- include "financials.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "financials.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "financials.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: migration
        image: migrate/migrate:{{ .Values.financials.migrate.image.tag }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          migrate \
          -path /etc/migrations \
          -database='postgres://{{ .Values.postgresql.postgresqlUsername }}:$(PG_PASSWORD)@{{ template "postgresql.host" . }}:5432/{{ .Values.postgresql.postgresqlDatabase }}?sslmode=disable' \
          up
        env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: postgresql-password
        volumeMounts:
        - name: migrations
          mountPath: /etc/migrations
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.financials.image.repository }}:{{ .Values.financials.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.financials.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /alive
            port: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http
        env:
        - name: CONFIG_FILE
          value: /etc/financials/config.yaml
        resources:
          {{- toYaml .Values.financials.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /etc/financials
      volumes:
      - name: config
        secret:
          secretName: {{ template "financials.fullname" .}}-config
      - name: migrations
        configMap:
          name: {{ .Release.Name }}-migrations
