[package]
name = "financials"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
csv = "1.1"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
