[package]
name = "financials"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.0.13", features = ["derive"] }
csv = "1.1"
diesel = { version = "1.4.8", features = ["postgres", "chrono"] }
diesel_migrations ="1.4.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
