[package]
name = "financials"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "3.0.13", features = ["derive"] }
csv = "1.1"
diesel = { version = "1.4.8", features = ["postgres"] }
diesel_migrations ="1.4.0"
serde = { version = "1.0", features = ["derive"] }
