openapi: 3.0.3
info:
  title: Login endpoints
  version: 0.0.1

path:

components:
  schemas:
    Error:
      description: Standard error object.
      properties:
        description:
          type: string
        message:
          type: string
    Paging:
      type: object
      properties:
        total:
          type: integer
          description: "Total number of results."
        page:
          type: integer
          description: "Current page number."
        pages:
          type: integer
          description: "Total number of pages."
