openapi: 3.0.3
info:
  title: Login endpoints
  version: 0.0.1

.tags: &tags
  - "Login"

paths:
  "/api/v1/users":
    post:
      tags: *tags
      operationID: CreateUser
      summary: "Creates a user and returns the session token"
      requestBody:
        description: An user object.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: Created
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session-token=somehashhere
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
        500:
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  "/api/v1/login":
    post:
      tags: *tags
      operationID: CreateUser
      summary: "Creates a user and returns the session token"
      requestBody:
        description: An user object.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: Success
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session-token=somehashhere
          content:
            application/json:
              schema:
                type: object
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
        500:
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  "/api/v1/logout":
    post:
      tags: *tags
      operationID: Logout
      summary: "Logs the user out"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  "/api/v1/session":
    get:
      tags: *tags
      operationID: CreateUser
      summary: "Creates a user and returns the session token"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

components:
  schemas:
    User:
      description: A user object that contains user information.
      properties:
        id:
          type: string
          readOnly: true
        created_at:
          type: "string"
          format: "date-time"
          readOnly: true
        updated_at:
          type: "string"
          format: "date-time"
          readOnly: true
        username:
          type: string
        password:
          type: string
          format: password
          writeOnly: true
