openapi: 3.0.3
info:
  title: Trade endpoints
  version: 0.0.1

.tags: &tags
  - "Trades"

paths:
  "/api/v1/trades":
    post:
      tags: *tags
      operationID: CreateTransactionInBulk
      summary: "Create trade transactions in bulk"
      requestBody:
        description: A list of trade transactions.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BulkTradeTransaction"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
        500:
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
    get:
      tags: *tags
      operationID: List
      summary: "Get trade transactions in bulk"
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: page_size
          schema:
            type: integer
            default: 1
        - in: query
          name: order_by
          schema:
            type: string
            default: "date_purchased"
        - in: query
          name: order
          schema:
            type: string
            default: "desc"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedTrades"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
        500:
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  "/api/v1/trades/portfolio":
    get:
      tags: *tags
      operationID: ListPortfolio
      summary: "Get trade transactions in bulk"
      parameters:
        - in: query
          name: from
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TradePortfolio"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
        500:
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

components:
  schemas:
    BulkTradeTransaction:
      description: Contains multiple trade transactions.
      properties:
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/Trade"
    Trade:
      description: A user object that contains user information.
      properties:
        id:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        date_purchased:
          type: string
          format: date-time
        symbol:
          type: string
        price_each:
          type: number
        quantity:
          type: number
        trade_type:
          $ref: "#/components/schemas/TradeType"

    PaginatedTrades:
      description: An object that contains all trades in a paginated list.
      allOf:
        - type: object
          properties:
            paging:
              $ref: "common.yaml#/components/schemas/Paging"
        - type: object
          properties:
            results:
              type: array
              items:
                $ref: "#/components/schemas/BulkTradeTransaction"

    TradeType:
      type: string
      enum:
        - buy
        - sell

    TradePortfolio:
      description: The portfolio and with the date and respective values.
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/SingleTradePortfolio"

    SingleTradePortfolio:
      properties:
        id:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        trade_date:
          type: string
          format: date-time
          readOnly: true
        symbol:
          type: string
          readOnly: true
        quantity:
          type: number
          readOnly: true
        principal:
          type: number
          readOnly: true
        nav:
          type: number
          readOnly: true
        simple_returns:
          type: number
          readOnly: true
