Server:
  Port: 8000
  WriteTimeoutInSeconds: 5s
  ReadTimeoutInSeconds: 5s
  ReactFilePath: "../ui/build"

Database:
  Host: localhost
  Port: 5432
  User: postgres
  Password: password
  Name: postgres
  TimeZone: Asia/Singapore
  BatchInsertSize: 100

AlphaVantageAPIKey: test
PortfolioCalculationInterval: 1h
