name: publish-container
on:
  push:
    branches:
    - master

jobs:
  publish-app:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/ashwinath
      RUST_VERSION: 1.65.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Rust ${{ env.RUST_VERSION }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.RUST_VERSION }}
        default: true
    - name: Run cargo test
      working-directory: financials
      run: make test
    - name: Setup GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and push
      working-directory: financials
      run: make

  publish-grafana-init:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/ashwinath
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and push
      working-directory: grafana
      run: make
